name: Actions Sandbox

on:
  workflow_dispatch:
    title:
      required: true
      disctription: 'Title'
  pull_request:
    branches:
      - master
    types:
      - closed


jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: send
        run: echo "Hello"